apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: super-duper-doodle
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
    - host: doodle.local  # replace with your domain or local hostname
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: super-duper-doodle
                port:
                  number: 80
