apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: super-duper-doodle
spec:
  ingressClassName: traefik
  rules:
    - host: sondregarnaes-hp-probook-450-g5.taild1fe38.ts.net
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
