server.port=8080

spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:5432/${DB_NAME:polldb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:supersecret}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
